# Change these first
owner: human-does
repo: mangobeds-status

sites:
  - name: Booking Form Health
    url: https://www.mangobeds.com/api/health/booking-forms
    delay: 5000 
    type: globalping
    location: europe
  - name: Main Website Health
    url: https://www.mangobeds.com/api/health/main    
    delay: 5000 
    type: globalping
    location: europe   
    
  #   - name: Web application
  #     url: https://mangobeds.com
  #   - name: Booking forms
  #     url: https://www.mangobeds.com/booking-forms/cmapiq1pe0001axse16wpwxp7
  - name: API
    url: https://api.mangobeds.com/health-check
  - name: Server
    url: $SERVER_URL/health-check
  - name: Job Manager
    url: $SERVER_URL/queues/health
  - name: Database
    url: $DATABASE_URL
    type: tcp-ping
    delay: 10000
    location: europe


workflowSchedule:
  uptime: "*/10 * * * *"  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org

  cname: status.mangobeds.com
  theme: light
  favicon: https://www.mangobeds.com/favicon.ico
  # baseUrl: /mangobeds-status
  baseUrl: /
  logoUrl: https://www.mangobeds.com/images/logo.png
  name: Status
  introTitle: Hospitality Tools That Pay for Themselves.
  introMessage: This is Mangobeds status page which uses **real-time** data.
  css: |
    /* Hide the entire Past Incidents section: any section that contains an incident link */
    section:has(a[href*="/incident/"]) { display: none !important; }

    /* Also hide the History link in the navbar (if present) */
    nav a[href*="/history"] { display: none !important; }
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: Dashboard
  #     href: https://mangobeds.com
      
# assignees:
#  - mangobeds

i18n:
  footer: "[Mangobeds](https://mangobeds.com)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
